[versions]
android-gradle-plugin = "8.11.2"
androidx-activity = "1.11.0"
androidx-compose = "1.7.8"
androidx-lifecycle = "2.8.6"
androidx-wear-compose = "1.5.3"
converter-moshi = "2.11.0"
core-splashscreen = "1.0.1"
dagger = "2.56.2"
datastore-preferences = "1.1.7"
health-services = "1.0.0"
horologist = "0.7.15"
kotlin = "2.1.21"
lifecycle-viewmodel-compose = "2.9.4"
logging-interceptor = "5.3.0"
moshi-kotlin = "1.15.2"
moshi-kotlin-codegen = "1.15.2"
navigation-compose = "2.9.5"
okhttp = "5.3.0"
org-jetbrains-kotlin = "2.1.21"
retrofit = "2.11.0"
ui-test-junit4 = "1.8.3"
robolectric = "4.14.1"
roborazzi = "1.45.1"
ksp = "2.1.21-2.0.1"
hilt = "2.56.2"
ktlint = "0.50.0"
core-ktx = "1.17.0"
compose-bom = "2024.09.00"
car-ui-lib = "2.6.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-navigation = "androidx.navigation:navigation-compose:2.8.4"
androidx-compose-runtime = "androidx.compose.runtime:runtime:1.7.5"
androidx-compose-ui-tooling = { module = "androidx.wear.compose:compose-ui-tooling", version.ref = "androidx-wear-compose" }
androidx-concurrent = "androidx.concurrent:concurrent-futures-ktx:1.2.0"
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore-preferences" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }
androidx-health-services = { module = "androidx.health:health-services-client", version.ref = "health-services" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle"}
androidx-lifecycle-extensions  = "androidx.lifecycle:lifecycle-extensions:2.2.0"
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle"}
androidx-lifecycle-runtime-compose = "androidx.lifecycle:lifecycle-runtime-compose:2.8.7"
androidx-lifecycle-service = {module = "androidx.lifecycle:lifecycle-service", version.ref = "androidx-lifecycle"}
androidx-lifecycle-viewmodel = {module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle"}
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidx-compose" }
androidx-navigation-compose-v295 = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-wear = "androidx.wear:wear:1.3.0"
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "ui-test-junit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "ui-test-junit4" }
compose-compiler = "androidx.compose.compiler:compiler:1.5.15"
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose" }
compose-wear-navigation = "androidx.wear.compose:compose-navigation:1.4.0"
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "converter-moshi" }
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger"}
dagger-hilt-android-compiler = {module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger"}
desugar-jdk-libs = "com.android.tools:desugar_jdk_libs:2.1.2"
guava = "com.google.guava:guava:33.3.1-android"
hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.2.0"
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
horologist-compose-layout = { module = "com.google.android.horologist:horologist-compose-layout", version.ref = "horologist" }
horologist-health-composables = { module = "com.google.android.horologist:horologist-health-composables", version.ref = "horologist" }
horologist-health-service = { module = "com.google.android.horologist:horologist-health-service", version.ref = "horologist" }
horologist-roboscreenshots = { module = "com.google.android.horologist:horologist-roboscreenshots", version.ref = "horologist" }
jacoco-ant = "org.jacoco:org.jacoco.ant:0.8.12"
junit = "junit:junit:4.13.2"
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor" }
material3 = { module = "androidx.compose.material3:material3" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi-kotlin" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi-kotlin-codegen" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
roborazzi = { group = "io.github.takahirom.roborazzi", name = "roborazzi", version.ref = "roborazzi" }
roborazzi-compose = { group = "io.github.takahirom.roborazzi", name = "roborazzi-compose", version.ref = "roborazzi" }
roborazzi-rule = { group = "io.github.takahirom.roborazzi", name = "roborazzi-junit-rule", version.ref = "roborazzi" }
test-espresso-core = "androidx.test.espresso:espresso-core:3.6.1"
test-ext-junit = "androidx.test.ext:junit:1.2.1"
ui = { module = "androidx.compose.ui:ui" }
wear-compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "androidx-wear-compose" }
wear-compose-material = { module = "androidx.wear.compose:compose-material3", version.ref = "androidx-wear-compose" }
wear-ongoing-activity = "androidx.wear:wear-ongoing:1.0.0"
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
car-ui-lib = { group = "com.android.car.ui", name = "car-ui-lib", version.ref = "car-ui-lib" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger"}
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin" }
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
com-diffplug-spotless = "com.diffplug.spotless:7.0.3"

